debug: false
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  messages:
    basename: i18n/config/config
logging:
  path: D:\\Java
  pattern:
    console: '%(%d{yyyy-MM-dd HH:mm:ss})  [%p]  %(%C:%L)  : %m %n'
    file: '%(%d{yyyy-MM-dd HH:mm:ss})  [%p]  %(%C:%L)  : %m %n'
  level:
    root: INFO
    org.springframework.web.servlet: WARN
  file:
    max-size: 15MB
    max-history: 10000